baseURL = "https://memills.com/"
languageCode = "en-us"
title = "M. E. Mills"
publishDir = "docs" 
enableGitInfo = true

# theming and reusable code
[module]
  [[module.imports]]
    path = "github.com/ajs17/hugo-min-components"
  [[module.imports]]
    path = "memills-theme"




